modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/easy-villagers/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/easy_villagers.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/easy-villagers"
authors="${mod_vendor}"
description='''Easy Villagers'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="theoneprobe"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"